### ISSUE TITLE
ascension mod only works for "the defect" character

### ISSUE THREAD

**Issue by ilovethismod** [will2216/Ascension-plus#10]
in standard mode i can only use ascension for "the defect" character. the other 2 characters theres no option for for ascension to be enabled.

also in custom mode the ascension only goes up, no way to select the easier versions below zero

**Comment by BetaChess** [comment]
I can't find any problem with ascension in standard mode. Custom mode is a known issue. Could you send your pref files?

**Comment by ilovethismod** [comment]
sorry if you could delete that comment, i solved the issue.

appaerently if you dont beat the game with that character the ascension
option wont show up

thats why only "the defect" character for me was showing the ascension mode
option because i beat the game before with him.

the others however I had not beaten the game with but as soon as i did on
vanilla, the ascension modes became available.

sorry about that.

**Comment by BetaChess** [comment]
Np, I'll see if I have time to make a config option for that. Enjoy the mod :)
