### ISSUE TITLE
Mod stopped showing in the UI, crashes when lowering level in Custom

### ISSUE THREAD

**Issue by DerpTheBugbear** [will2216/Ascension-plus#11]
Everything was working fine yesterday. As of today, the UI elements for this mod have stopped showing up.  I can still go into "Custom Game" and change the Ascension Level, but the number doesn't update unless I hover over the checkbox to the left of the Ascension level option.  I can increase the level just fine, but if I try to lower the level below zero (-1, -2, etc.) it instantly crashes.
I have quite a few mods, but it's been working just fine until today. 

The only thing that has changed since yesterday was 'Minty Spire (QoL Compilation)' had an update this morning.  Not sure if that did it.
[SlayTheSpire - copy 1.txt](https://github.com/will2216/Ascension-Reborn/files/3714950/SlayTheSpire.-.copy.1.txt)

**Comment by DerpTheBugbear** [comment]
ModTheSpire and BaseMod also recently had an update, but that was on the 7th and 8th respectively. I was able to use this mod just fine on the 9th.

**Comment by DerpTheBugbear** [comment]
I disabled the mod, loaded the game without it, then re-enabled it and it seems to show up just fine in the UI now, and I can lower the level past 0, however I'm still getting a crash when lowering the level in the custom game screen.


Specifically, the steps I take to reproduce the UI displaying "Level 0" instead of the selected level are:
1. Go to Custom
![20191010184104_1](https://user-images.githubusercontent.com/56416251/66614640-69d61800-eb8f-11e9-9f03-2ac57f2718a9.jpg)

2. Click the arrow to raise the Ascension Level (notice it doesn't update the displayed level to the left of the arrows, but it updates the effect to their right. "Elites spawn more often." is displayed)
![20191010184124_1](https://user-images.githubusercontent.com/56416251/66614670-840ff600-eb8f-11e9-8495-1357b83afbfa.jpg)

3. Hover cursor over checkbox to see the UI display the correct Ascension Level. (Moving the cursor off of the checkbox reverts the displayed level back to 0)
![20191010184127_1](https://user-images.githubusercontent.com/56416251/66614687-9427d580-eb8f-11e9-9773-d146d2cc9f3c.jpg)


Steps I take to reproduce the crash are:
1. Go to Custom
![20191010184104_1](https://user-images.githubusercontent.com/56416251/66614640-69d61800-eb8f-11e9-9f03-2ac57f2718a9.jpg)

2. Click the arrow to lower the Ascension Level (Level still displayed as 0, but displays the correct effect)
![20191010184138_1](https://user-images.githubusercontent.com/56416251/66614740-c5080a80-eb8f-11e9-84e2-c2c433523e44.jpg)

3. Hover cursor over checkbox to see the UI display the correct level while simultaneously crashing to desktop.

**Comment by DerpTheBugbear** [comment]
Figured out some more info on the original issue I had with the Ascension Level selection UI elements not showing up at all.

Looks like it's not showing up at all on any modded characters; nor is it showing for The Defect.  I erroneously thought I had fixed the issue because I had originally wanted to do a Defect run, saw I could not select Ascension Level, then on disabling and re-enabling I checked one of the other two official characters. I only just now checked The Defect again, which then prompted me to check the modded characters as well.  

It's possible some mod I have makes changes to the Defect such that whatever is causing level selection to bug out on modded characters is also causing the same to happen to The Defect?

Ascension Level selection at the bottom in the middle (The Silent):
![20191010214223_1](https://user-images.githubusercontent.com/56416251/66620687-00fa9a00-eba7-11e9-9bfb-c6fc53948e86.jpg)

No Ascension Level selection for modded characters (such as Beaked The Cultist):
![20191010214233_1](https://user-images.githubusercontent.com/56416251/66620729-32736580-eba7-11e9-9320-d104da94b20b.jpg)

Similarly, no Ascension Level selection for The Defect:
![20191010214227_1](https://user-images.githubusercontent.com/56416251/66620762-5171f780-eba7-11e9-81cd-3933a5a7f534.jpg)

**Comment by BetaChess** [comment]
I'm gonna try to fix as much of this as possible in my vacation. But the last thing isn't actually a "bug" per say. I don't think you've unlocked ascension on the characters. Thus, it isn't showing up as an option. I'll look into the crash though, since that should definitely not be happening. And I'll try to add some things to generally make the mod a bit better. Just wish I had more time.

**Comment by BetaChess** [comment]
It seems like I've fixed the problem, but please open another issue if it persists. Just pushed an update
