### ISSUE TITLE
Incorrect Update URL

### ISSUE THREAD

**Issue by kiooeht** [will2216/Ascension-plus#2]
The `update_json` url in your `ModTheSpire.json` is incorrect and causes ModTheSpire to fail and hang trying to find updates for all mods (see https://github.com/kiooeht/ModTheSpire/issues/74).

Your `update_json` should be `"https://api.github.com/repos/will2216/Ascension-plus/releases/latest"`

**Comment by BetaChess** [comment]
Fixed
